name: Scheduled Update of Release Notes

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"  # 每天UTC时间1点运行一次，即北京时间10点

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: pip install requests pandas pyyaml jq

      - name: Run auto-release-notes.py script
        run: |
          IFS=',' read -r APP_ID APP_SECRET URL <<< "${{ secrets.FEISHU_SECRET }}"
          FILENAME="${{ secrets.RELEASE_NOTES_FILE }}"
          export APP_ID APP_SECRET URL FILENAME  # 导出为环境变量
          python scripts/auto-release-notes.py

      - name: Check if changes, commit and push
        id: compare
        run: |
          if git diff --quiet origin/main -- docs/zh/docs/rel-notes.md; then
            echo "files_are_same=true" >> $GITHUB_OUTPUT
            echo "No changes to commit"
          else
            echo "files_are_same=false" >> $GITHUB_OUTPUT
            # git config --global user.name "github-actions[bot]"
            # git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
            DATE=$(date +%Y%m%d)
            BRANCH="update-rel-notes-$DATE"
            git checkout -b "$BRANCH" || git checkout "$BRANCH"
            git commit -m "Update rel-notes.md via automation"
            git push -u origin update-rel-notes --force
            echo "branch=$BRANCH" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request
        if: steps.compare.outputs.files_are_same == 'false'
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update rel-notes.md via automation"
          title: "Automated update of rel-notes.md"
          body: "This PR updates rel-notes.md automatically."
          base: main
          branch: ${{ steps.compare.outputs.branch }}
          # delete-branch: true